---
name: 'build-push'

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN_ECR_PUBLIC }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
  OWNER: h7d7l6t4
  GROUP: base
  FILE: alpine-ci

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: 'setup qemu'
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: 'setup docker buildx'
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: 'configure aws credentials'
        uses: aws-actions/configure-aws-credentials
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: "GitHubActions-${{ github.event.repository.owner.login }}-${{ github.event.repository.name }}-${{ github.run_id }}"
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: 'login to amazon ecr'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login
        with:
          registry-type: public

      - name: 'login to dockerhub'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_SECRET }}

      - name: 'extract version from dockerfile'
        id: extract_version
        run: |
          TAG=$(sed -n 's/^ARG BASE_VERSION=v\?\([0-9.]*\).*/\1/p' Dockerfile)
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "TAG=${TAG#v}"

      - name: 'push'
        uses: docker/bake-action@2e3d19baedb14545e5d41222653874f25d5b4dfb # v5
        with:
          targets: push
